version: "3.5"
services:
  main:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  face-bokeh:
    build:
      context: ./face-bokeh
    ports:
      - "8001:8000"
  face-emotion:
    build:
      context: ./face-emotion
    ports:
      - "8002:8000"
  triton:
    image: nvcr.io/nvidia/tritonserver:22.06-py3
    ports:
      - "8003:8002"
    command:
      [
        "tritonserver --model-repository=s3://triton-repository/models/"
      ]
