version: "3.5"
services:
  main:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  face-bokeh:
    build:
      context: ./face-bokeh
    ports:
      - "8001:8000"
  face-emotion:
    build:
      context: ./face-emotion
    ports:
      - "8002:8000"
